name: NuGet

on:
  workflow_dispatch:

jobs:
  build-espeak:
    runs-on: ubuntu-latest

    name: "Linux ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]

        include:
          - os: ubuntu
            osver: 22.04
            sys: linux-gnu

          - arch: amd64
            ccarch: x86_64
            nugetarch: x64
            archcflags: ""
            cross: no

    steps:

    # Linux - dependencies
    - name: apt-build-deps
      if: matrix.os == 'ubuntu' && matrix.arch != 'amd64'
      run: |
        [ 'x${{ matrix.cross }}' == 'xno' ] && sudo dpkg --add-architecture ${{ matrix.arch }}
        sudo apt-get update
        sudo apt-get install ronn kramdown python3
    - name: apt-arch-deps
      if: matrix.os == 'ubuntu' && matrix.cross == 'no'
      run: "sudo apt-get install cmake valgrind g++-12-multilib linux-libc-dev:${{ matrix.arch }} libpcaudio-dev:${{ matrix.arch }} libsonic-dev:${{ matrix.arch }} libc6-dbg:${{ matrix.arch }} libgcc-s1:${{ matrix.arch }}"
    - name: apt-cross-deps
      if: matrix.os == 'ubuntu' && matrix.cross == 'yes'
      run: sudo apt-get install qemu-user g++-12-${{ matrix.arch }}-${{ matrix.sys }}

    # Checkout code
    - uses: actions/checkout@v7

    # Configure
    - name: configure
      run: |
        export CC="${{ matrix.ccarch }}-${{ matrix.sys }}-gcc-12"
        export CXX="${{ matrix.ccarch }}-${{ matrix.sys }}-g++-12"
        [ 'x${{ matrix.cross }}' = 'xyes' ] && export LD="${{ matrix.ccarch }}-${{ matrix.sys }}-ld"
        export CFLAGS="-g -Og -fno-omit-frame-pointer ${{ matrix.archcflags }}"
        export CXXFLAGS="-g -Og -fno-omit-frame-pointer ${{ matrix.archcflags }}"
        cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} -DUSE_ASYNC:BOOL=OFF

    # Build and test
    - name: make-binary
      run: cmake --build build --target espeak-ng
    - name: make-data
      run: cmake --build build --target data
    - name: test
      run: |
        cmake --build build --target tests
        ctest --test-dir build -T test -j8 --output-on-failure

    - name: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: espeak-ng
        path: build

  build-pcaudio:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        repository: jonko0493/pcaudiolib
    
    - name: apt-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-dev libasound2-dev

    - name: build
      run: |
        ./autogen.sh
        ./configure --prefix=$(pwd) --with-pulseaudio --with-alsa
        make
        make install

    - name: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: pcaudio
        path: lib

  build-sonic:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        repository: jonko0493/sonic
    
    - name: build
      run: make sonic all
    
    - name: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: sonic
        path: ${{ github.workspace }}

  release:
    runs-on: ubuntu-latest
    needs: [build-espeak, build-pcaudio, build-sonic]
    steps:
      - name: checkout-repo
        uses: actions/checkout@v7
        with:
          path: repo
          

      - name: download-espeak-ng
        uses: actions/download-artifact@v8
        with:
          name: espeak-ng
          path: espeak-ng
      
      - name: download-pcaudio
        uses: actions/download-artifact@v8
        with:
          name: pcaudio
          path: pcaudio
      
      - name: download-sonic
        uses: actions/download-artifact@v8
        with:
          name: sonic
          path: sonic
      
      - name: create-nupkg
        run: |
          mkdir -p nuget/build
          mkdir -p nuget/lib/net10.0
          mkdir -p nuget/runtimes/linux-x64/native
          mkdir -p nuget/data

          cp -L espeak-ng/src/libespeak-ng/libespeak-ng.so nuget/runtimes/linux-x64/native/libespeak-ng.so
          cp -L pcaudio/libpcaudio.so nuget/runtimes/linux-x64/native/libpcaudio.so.0
          cp -L sonic/libsonic.so nuget/runtimes/linux-x64/native/libsonic.so.0

          cp -r espeak-ng/espeak-ng-data nuget/data/

          cp repo/COPYING nuget/LICENSE.txt
          cp repo/espeak-ng.nuspec nuget/espeak-ng.nuspec
          cp repo/espeak-ng.targets nuget/build/espeak-ng.targets

          cd nuget && zip -r ../espeak-ng.nupkg *

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: nuget
          path: espeak-ng.nupkg

      - name: nuget-push
        run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.intothedreamspring.com/v3/index.json ./espeak-ng.nupkg